// <auto-generated />
using ElCatoWebApi.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ElCatoWebApi.Models.OldModels.Compiled
{
    [DbContext(typeof(OldDbContext))]
    public partial class OldDbContextModel : RuntimeModel
    {
        static OldDbContextModel()
        {
            var model = new OldDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static OldDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
