// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ElCatoWebApi.Models.OldModels.Compiled
{
    public partial class OldDbContextModel
    {
        partial void Initialize()
        {
            var card = CardEntityType.Create(this);
            var cardListItem = CardListItemEntityType.Create(this);
            var homeAlert = HomeAlertEntityType.Create(this);
            var page = PageEntityType.Create(this);

            CardListItemEntityType.CreateForeignKey1(cardListItem, card);
            CardListItemEntityType.CreateForeignKey2(cardListItem, page);

            CardEntityType.CreateAnnotations(card);
            CardListItemEntityType.CreateAnnotations(cardListItem);
            HomeAlertEntityType.CreateAnnotations(homeAlert);
            PageEntityType.CreateAnnotations(page);

            AddAnnotation("ProductVersion", "7.0.9");
        }
    }
}
