// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ElCatoWebApi.Models.Compiled
{
    public partial class AppDbContextModel
    {
        partial void Initialize()
        {
            var card = CardEntityType.Create(this);
            var page = PageEntityType.Create(this);
            var section = SectionEntityType.Create(this);
            var user = UserEntityType.Create(this);

            CardEntityType.CreateForeignKey1(card, section);
            PageEntityType.CreateForeignKey1(page, card);

            CardEntityType.CreateAnnotations(card);
            PageEntityType.CreateAnnotations(page);
            SectionEntityType.CreateAnnotations(section);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "7.0.9");
            AddAnnotation("Proxies:ChangeTracking", false);
            AddAnnotation("Proxies:CheckEquality", false);
            AddAnnotation("Proxies:LazyLoading", true);
        }
    }
}
