name: Create Pages Branch

on:
  push:
    branches:
      - main

jobs:
  create-pages-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Create Pages Branch
        run: |
          git branch pages
          git checkout pages
          git push origin pages
          
      - name: Copy files to Pages Branch
        run: |
          cp -R ElCatoWebApi/ElCatoWebApi/wwwroot/react/* .
          git add .
          git commit -m "Copy files to Pages Branch"
          git push origin pages
